version: '3'
services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: .
    container_name: flask_app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  pgdata: